### PR TITLE
Added a KillAura check. May need some tweaks 

### PR DESCRIPTION
**Pull request by Pixchure**
I ported a KillAura check from another anticheat probably needs some fixing.

### CODE REVIEW

**Comment by katekerllenevich** [comment]
this is better as a BadPackets check, as it checks if the protocol is invalid

**Comment by Pixchure** [comment]
Oh ok

**Comment by Pixchure** [comment]
Ok I added an autoclicker check. I hope it works, it flags if a player clicks over 35 CPS

**Review by JustDoom — COMMENTED** [review]
seems fine, I'll make a few changes and make sure it all works and probably release this with the next update

**Comment by Pixchure** [comment]
> seems fine, I'll make a few changes and make sure it all works and probably release this with the next update

Ok

**Comment by JustDoom** [comment]
lol that was fast

**Comment by JustDoom** [comment]
the killaura check is already in this anticheat as badpackets b

**Comment by Pixchure** [comment]
> the killaura check is already in this anticheat as badpackets b

Oh ok. I guess you can just remove it I guess. Btw I’ll try and add more checks. Also can you get these checks to work with the config.yml? I couldn’t figure out how

**Comment by JustDoom** [comment]
I can get them working

**Comment by JustDoom** [comment]
@Pixchure also im not sure if i can get your version of the autoclicker working as half the code needs code from wherever you got it from. sorry

**Pull request merged**
