### PR TITLE
Added checks

### PR DESCRIPTION
**Pull request by SalersFR**

### CODE REVIEW

**Comment by amnoah** [comment]
FlyB is basically Medusa FlyB
https://github.com/GladUrBad/Medusa/blob/master/Impl/src/main/java/com/gladurbad/medusa/check/impl/movement/fly/FlyB.java

**Comment by SalersFR** [comment]
idfk i blindly coded it lol

and stop saying that i skid everything

you're toxic asf

**Comment by SalersFR** [comment]
but okay if you want, so i'll close this pull request and go be fucked for having help with this ac

do you want that ?

**Comment by ghost** [comment]
> FlyB is basically Medusa FlyB
> https://github.com/GladUrBad/Medusa/blob/master/Impl/src/main/java/com/gladurbad/medusa/check/impl/movement/fly/FlyB.java

Yo did you know that basically EVERYONE uses a same Y fly check?
Crazy man.
Letting ya know that I also have something similar to this :D


 EDIT: I realized this FlyB is not the same as FlappyAC's FlyB, ignore me hehe

**Review by JustDoom — APPROVED** [review]

**Pull request merged**
